[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cieinr"
authors = [
    {name = "Adam Graefe", email="adam.graefe@charite.de"},
     ]
description = "This repository houses the LinkML representation of the data model for the Canadian Inborn Errors of Immunity National Registry (CIEINR). This project facilitates the export of patient data into Phenopackets, leveraging RareLink's functionalities."
readme = "README.md"
requires-python = ">=3.10, <3.13"
version = "1.0.0.dev0"
keywords = [
    "Inborn Errors of Immunity",
    "GA4GH Phenopackets",
    "Canadian Inborn Errors of Immunity National Registry",
    "Ontologies",
    "Interoperability",
    "HL7 FHIR"
]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3 :: Only",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Medical Science Apps."
]
dependencies = [
    "pytest",
    "rarelink",
    "typer>=0.9.0",
    "python-dotenv>=1.0.0",
    "requests>=2.31.0",
    "phenopackets>=2.0.2.post5",
    "protobuf>=3.20.2",
    "linkml>=1.9",
    "linkml-runtime",
    "oaklib>=0.5.26",
    "tqdm>=4.66.0",
    "pyyaml>=6.0.1",
    "pyphetools>=0.3.3",
]

[project.optional-dependencies]
test = ["pytest>=7.0.0,<8.0.0", "pytest-cov"]
docs = ["sphinx>=7.0.0", "sphinx-rtd-theme>=1.3.0", "sphinx-copybutton>=0.5.0"]

# Removed project.urls section since it had empty values

[tool.setuptools]
package-dir = { "" = "src" }

# The following would provide a command line executable called `sample`
# which executes the function `main` from this package when invoked.
[project.scripts]
cieinr = "cieinr.cli.app:main"