[pytest]
norecursedirs =
    docs
    submodules
    build
    src/cieinr/v1_0_0/python_schemas
python_files = _test*.py test*.py
addopts = --doctest-modules --doctest-glob *.rst
- name: Set warning filter
  run: |
    export PYTHONWARNINGS="ignore::DeprecationWarning"